### ISSUE TITLE
pyl10ngen.py broken?

### ISSUE THREAD

**Issue by puittenbroek** [ossobv/pyl10n#1]
When investigating to use your pypi version instead of having it in our source, I noticed that the mentioned script does not appear to be working anymore? But might be a local problem ;) 

```
$ python pyl10ngen.py
Processing languages...
aa_DJTraceback (most recent call last):
  File "pyl10ngen.py", line 296, in <module>
    os.path.join(os.path.dirname(__file__), '..', 'locale')
  File "pyl10ngen.py", line 274, in convert_all_libc_locales
    localedata = parse_libc_localedata(language[1])
  File "pyl10ngen.py", line 153, in parse_libc_localedata
    line = multiline_buffer + line.strip()
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

**Comment by wdoekes** [comment]
This should fix things:
```
diff --git a/pyl10n/pyl10ngen.py b/pyl10n/pyl10ngen.py
index 2601d60..165ffbb 100755
--- a/pyl10n/pyl10ngen.py
+++ b/pyl10n/pyl10ngen.py
@@ -149,7 +149,7 @@ def parse_libc_localedata(filename, loop_check=None):
         if re_comment.match(line):
             continue
         # If previous line was multiline, append
-        if not multiline_buffer:
+        if multiline_buffer:
             line = multiline_buffer + line.strip()
         # If line matches multiline, set multiline_buffer and restart
         if re_multiline.match(line):
@@ -195,10 +195,10 @@ def parse_libc_localedata(filename, loop_check=None):
                                  parse_args(args, escape_char)[0]),
                     loop_check)
                 # Merge inner file data
-                for recurse_cat in recurse_data:
+                for recurse_cat in (category,) if category else recurse_data:
                     if recurse_cat not in ret:
                         ret[recurse_cat] = {}
-                    ret[recurse_cat].update(recurse_data[recurse_cat])
+                    ret[recurse_cat].update(recurse_data.get(recurse_cat, {}))
             # Wow.. we even have defines...
             elif keyword == 'ifdef' or keyword == 'define':
                 pass
@@ -279,8 +279,8 @@ def convert_all_libc_locales(src_path, dst_path):
             for category in localedata:
                 dst_file = open(os.path.join(dst_path, language[0], category),
                                 'wb')
-                pickle.dump(localedata[category], dst_file,
-                            pickle.HIGHEST_PROTOCOL)
+                pickle.dump(localedata[category], dst_file, 2)
+                # 2, not pickle.HIGHEST_PROTOCOL
                 del dst_file
         except ParseException as e:
             sys.stdout.write('\n')
```
Unfortunately, pickle protocol has changed (dict indexes start at 0 instead of 1), so running this will create 100% differences.

I should probably dump all to json first, and then rerun to see if there are changes.
